name: stella_constellation_quiz
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.4+5

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  audioplayers: ^6.7.0

  # Monetisation
  google_mobile_ads: ^8.0.0
  in_app_purchase: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/constellations/
    - assets/avatars/
    - assets/audio/
    - assets/constellation_icons/
    - assets/app_icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon/stella_icon.png"
  adaptive_icon_background: "#071426"
  adaptive_icon_foreground: "assets/app_icon/stella_icon_foreground.png"